version: '3.8'

services:
  frpc:
    image: snowdreamtech/frpc:0.61.0
    container_name: piggy_frpc
    restart: always
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml:ro
    network_mode: host
